dashboard/dashboard/urls.py
from django.conf.urls import patterns, url
from dashboard.views import IndexView, Reports, VirtualMachineView, \
    ScanningReportReceiver, UpgradeReportReceiver, SVAInformationReceiver, FileView, SVAPlan, OvalReportReceiver, \
    OpenVasReportReceiver
urlpatterns = patterns('',
                       url(r'^$', IndexView.as_view(), name='dashboard_index'),
                       url(r'^virtual_machines/$', VirtualMachineView.as_view(), name='virtual_machines'),
                       url(r'^(?P<virtual_machine_number>[0-9]+)/reports/$', Reports.as_view(), name='reports'),
                       url(r'^scanning_report_post/$', ScanningReportReceiver.as_view(), name='upgrade_report_receiver'),
                       url(r'^upgrade_report_post/$', UpgradeReportReceiver.as_view(), name='upgrade_report_receiver'),
                       url(r'^oval_report_post/$', OvalReportReceiver.as_view(), name='oval_report_receiver'),
                       url(r'^openvas_report_post/$', OpenVasReportReceiver.as_view(), name='openvas_report_receiver'),
                       url(r'^sva_information/$', SVAInformationReceiver.as_view(), name='sva_information'),
                       url(r'^files/(?P<virtual_machine_number>[0-9]+)/(?P<name>.*)$', FileView.as_view(), name='file'),
                       url(r'^plan/$', SVAPlan.as_view(), name='plan'),
                       )

dashboard/dashboard_web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dashboard.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('dashboard.urls')),
)

dashboard/dashboard/models.py
import time
from managers import SVAInformationManager, ListReportManager, ExtendedScanReportManager, \
    ScanReportManager, UpReportManager, CveManager, VirtualMachineManager
from django.utils import timezone
from scanning_report_parser import ScanningReportGenerator
from upgrade_report_parser import UpgradeReportGenerator
from django.db import models
from django.db.models import Max


def generated_content(instance, filename):
    return '{0}/{1}/{2}'.format(instance.get_folder_name(), instance.virtual_machine.ip,
                                time.strftime(instance.get_folder_name() + '_%d_%m_%Y_%H_%M.json', time.localtime()))


def raw_content(instance, filename):
    return '{0}/{1}/{2}'.format(instance.get_folder_name(), instance.virtual_machine.ip,
                                time.strftime(instance.get_folder_name() + '_%d_%m_%Y_%H_%M.xml', time.localtime()))


def plan(instance, filename):
    return '{0}/{1}/{2}'.format(instance.get_folder_name(), instance.virtual_machine.ip,
                                time.strftime('plan_%d_%m_%Y_%H_%M.json', time.localtime()))


class VirtualMachine(models.Model):
    ip = models.IPAddressField()
    is_online = models.BooleanField(default=True)

    objects = VirtualMachineManager()


class SVAInformation(models.Model):
    virtual_machine = models.ForeignKey(VirtualMachine, on_delete=models.CASCADE)
    list_age_sva_msr2 = models.DateTimeField(null=True, verbose_name='List age')
    report_basic_age_sva_msr1 = models.DateTimeField(null=True, verbose_name='Basic scan age')
    up_report_age_sva_msr4 = models.DateTimeField(null=True, verbose_name='Upgrade report age')
    current_repository = models.CharField(max_length=100, null=True, verbose_name='Current repository')

    list_update_frequency = models.IntegerField(null=True, verbose_name='List update frequency')
    basic_scan_frequency = models.IntegerField(null=True, verbose_name='Basic scan frequency')
    extended_scan_frequency = models.IntegerField(null=True, verbose_name='Extended scan frequency')
    upgrade_report_frequency = models.IntegerField(null=True, verbose_name='Upgrade report frequency')

    list_availability_sva_msr7 = models.NullBooleanField(verbose_name='List available')
    up_report_availability_sva_msr10 = models.NullBooleanField(verbose_name='Upgrade report available')
    scan_report_availability_sva_msr9 = models.NullBooleanField(verbose_name='Scan report available')
    repository_availability_sva_msr6 = models.NullBooleanField(verbose_name='Repository available')
    scanner_availability_sva_msr8 = models.NullBooleanField(verbose_name='Scanner available')
    plan = models.FileField(null=True, upload_to=plan, verbose_name='Plan')
    objects = SVAInformationManager()

    @staticmethod
    def get_folder_name():
        return 'plan'


class Report(models.Model):
    GENERATING = 0
    FINISHED = 1
    TERMINATED = 2
    STATUS_CHOICES = (
        (GENERATING, "Generating"),
        (FINISHED, "Finished"),
        (TERMINATED, "Terminated"),
    )
    virtual_machine = models.ForeignKey(VirtualMachine, on_delete=models.CASCADE)
    time_added = models.DateTimeField(auto_now_add=True)
    task_id = models.CharField(max_length=200)
    status = models.SmallIntegerField(choices=STATUS_CHOICES, default=GENERATING)
    raw_content = models.FileField(null=True, upload_to=raw_content)

    def get_total_seconds(self):
        return (timezone.now() - self.time_added).total_seconds()

    def get_status(self, frequency):
        f = int(frequency) * 3600
        if self.get_total_seconds() > f:
            return 'VIOLATION'
        return 'OK'


class ExtendedScanReport(Report):
    objects = ExtendedScanReportManager()

    @staticmethod
    def get_folder_name():
        return 'extended_scan'


class ListReport(Report):
    objects = ListReportManager()

    @staticmethod
    def get_folder_name():
        return 'list_update'


class UpgradeReport(Report):
    objects = UpReportManager()

    def generate_report(self, results, available_updates):
        return UpgradeReportGenerator.generate_upgrade_report(self, results, available_updates)

    @staticmethod
    def get_folder_name():
        return 'upgrade_report'


class ScanReport(Report):
    objects = ScanReportManager()

    def generate_report(self, results):
        ScanningReportGenerator.generate_scanning_report(self, results)

    def get_vulnerability_size(self):
        return self.definition_set.count()

    def get_max_cvss(self):
        return self.definition_set.aggregate(max_cvss=Max('cve__cvss'))['max_cvss']

    @staticmethod
    def get_folder_name():
        return 'scan_report'


class Cve(models.Model):
    cve = models.CharField(max_length=128, db_index=True)
    cvss = models.FloatField(null=True)
    objects = CveManager()


class Definition(models.Model):
    scan_report = models.ForeignKey(ScanReport)
    definition_id = models.CharField(max_length=512, db_index=True)
    description = models.CharField(max_length=2048)
    cve = models.ForeignKey(Cve, null=True)
    vulnerability_result = models.NullBooleanField()

    class Meta:
        unique_together = (("scan_report", "definition_id"),)


class Package(models.Model):
    definitions = models.ManyToManyField(Definition, null=True)
    package_id = models.CharField(max_length=128)
    name = models.CharField(max_length=1024)
    version = models.CharField(max_length=128)
    available_version = models.CharField(max_length=128)


class UpgradeablePackage(models.Model):
    upgrade_report = models.ForeignKey(UpgradeReport)
    package_id = models.CharField(max_length=128)
    name = models.CharField(max_length=1024)
    current_version = models.CharField(max_length=128)
    available_version = models.CharField(max_length=128)

    class Meta:
        unique_together = (("upgrade_report", "package_id"),)

dashboard/dashboard/views.py
import logging
from django.views.generic import TemplateView, View
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from models import ScanReport, UpgradeReport, Cve, SVAInformation, VirtualMachine, ListReport, ExtendedScanReport, \
    Report
from tasks import generate_scanning_report, generate_upgrade_report, generate_oval_report, generate_openvas_report
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.http import StreamingHttpResponse
from django.core.servers.basehttp import FileWrapper
from common.utils import save_file
import os
import json
import constants
log = logging.getLogger(__name__)


def get_ip_address(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        return x_forwarded_for.split(',')[-1].strip()
    return request.META.get('REMOTE_ADDR')


def get_slo_by_name(plan, *names):
    slos = []
    try:
        for slo in plan['raw_data']['slos']:
            for name in names:
                if name in slo['metric_id']:
                    slos += [slo]
    except KeyError:
        return {}
    return slos


class IndexView(TemplateView):
    template_name = 'dashboard/index.html'

    def dispatch(self, request, *args, **kwargs):
        return redirect('virtual_machines')


class VirtualMachineView(TemplateView):
    template_name = 'dashboard/virtual_machines.html'

    def get_context_data(self, **kwargs):
        context = super(VirtualMachineView, self).get_context_data(**kwargs)
        vms = VirtualMachine.objects.all_with_reports()
        virtual_machines = []
        for virtual_machine in vms:
            ip = virtual_machine.ip
            virtual_machine_id = virtual_machine.id

            oval_report = ListReport.objects.get_last_finished_report(virtual_machine)
            scanning_report = ScanReport.objects.get_last_finished_report(virtual_machine)
            upgrade_report = UpgradeReport.objects.get_last_finished_report(virtual_machine)

            sva_information = SVAInformation.objects.get(virtual_machine=virtual_machine)
            plan = json.loads(sva_information.plan.read())

            basic_scan, list_update, up_report = get_slo_by_name(plan, 'basic_scan', 'list_update', 'up_report')

            virtual_machine = {'ip': ip,
                               'vulnerabilities_length': scanning_report.get_vulnerability_size(),
                               'max_cvss_score': scanning_report.get_max_cvss(),
                               'is_online': virtual_machine.is_online,
                               'id': virtual_machine_id,
                               'plan': plan.get('raw_data', {}),
                               'basic_scan': basic_scan,
                               'list_update': list_update,
                               'up_report': up_report,
                               'scanning_report': scanning_report,
                               'upgrade_report': upgrade_report,
                               'list_report': oval_report,
                               'basic_scan_status': scanning_report.get_status(basic_scan['value']),
                               'list_update_status': oval_report.get_status(list_update['value']),
                               'up_report_status': upgrade_report.get_status(up_report['value']),
                               'sva_information': sva_information,
                               'current_repository': sva_information.current_repository,
                               'plan_url': reverse('file', kwargs={'virtual_machine_number': virtual_machine_id,
                                                                   'name': 'plan'}),
                               'report_url': reverse('reports',
                                                     kwargs={'virtual_machine_number': virtual_machine_id})
                               }
            virtual_machines.append(virtual_machine)
            context['current_repository'] = sva_information.current_repository

        context['virtual_machines_json'] = virtual_machines
        context['dashboard_url'] = self.request.build_absolute_uri('/')
        return context


class Reports(TemplateView):
    template_name = 'dashboard/reports/report.html'

    def __init__(self):
        super(Reports, self).__init__()
        self.virtual_machine = None

    def get(self, request, *args, **kwargs):
        try:
            self.virtual_machine = VirtualMachine.objects.get(id=kwargs['virtual_machine_number'])
        except VirtualMachine.DoesNotExist:
            return redirect('virtual_machines')
        return super(Reports, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Reports, self).get_context_data(**kwargs)

        oval_report = ListReport.objects.get_last_finished_report(self.virtual_machine)
        scanning_report = ScanReport.objects.get_last_finished_report(self.virtual_machine)
        upgrade_report = UpgradeReport.objects.get_last_finished_report(self.virtual_machine)
        # extended_scan_report = ExtendedScanReport.objects.get_last_finished_report(self.virtual_machine)
        # try:
        #     extended_scan_report_json = ast.literal_eval(extended_scan_report.raw_content.read())
        #     context['extended_scan_report'] = extended_scan_report_json
        #     context['extended_scan_rows'] = range(' '.join(extended_scan_report_json['data']).count('scan_nvt_version'))
        # except:
        #     pass

        # Sort by cvss descending order
        context['scanning_report'] = scanning_report.definition_set.all().exclude(cve__cvss__isnull=True).order_by(
            '-cve__cvss', 'definition_id')
        context['upgrade_report'] = upgrade_report.upgradeablepackage_set.all()
        try:
            sva_information = SVAInformation.objects.get(virtual_machine=self.virtual_machine)
            context['scanning_report_age'] = scanning_report.time_added
            context['upgrade_report_age'] = upgrade_report.time_added
            context['oval_age'] = oval_report.time_added
            context['list_update_frequency'] = sva_information.list_update_frequency
            context['upgrade_report_frequency'] = sva_information.upgrade_report_frequency
            context['basic_scan_frequency'] = sva_information.basic_scan_frequency
        except SVAInformation.DoesNotExist:
            pass
        context['ip'] = self.virtual_machine.ip
        return context


class FileView(TemplateView):
    def response_download(self, file):
        the_file = file.path
        filename = os.path.basename(the_file)
        chunk_size = 8192
        response = StreamingHttpResponse(FileWrapper(open(the_file), chunk_size),
                                         content_type='application/force-download')
        response['Content-Length'] = os.path.getsize(the_file)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response

    def get(self, request, *args, **kwargs):
        virtual_machine = VirtualMachine.objects.get(id=kwargs['virtual_machine_number'])
        name = kwargs['name']
        if name == 'oval':
            return self.response_download(ListReport.objects.get_last_finished_report(virtual_machine).raw_content)
        if name == 'scanning_report':
            return self.response_download(ScanReport.objects.get_last_finished_report(virtual_machine).raw_content)
        if name == 'upgrade_report':
            return self.response_download(UpgradeReport.objects.get_last_finished_report(virtual_machine).raw_content)
        if name == 'extended_scan_report':
            return self.response_download(ExtendedScanReport.objects.get_last_finished_report(virtual_machine).raw_content)
        if name == 'plan':
            return HttpResponse(
                json.dumps(json.loads(SVAInformation.objects.get(virtual_machine=virtual_machine).plan.read()), indent=2),
                content_type='application/json')
        return redirect('dashboard_index')


class PostReceiver(TemplateView):
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(PostReceiver, self).dispatch(request, *args, **kwargs)


class OvalReportReceiver(PostReceiver):
    """
    Receives oval vulnerability list,
    saves it to database
    """

    def post(self, request, *args, **kwargs):
        sender_ip = get_ip_address(request)
        if 'file' in request.FILES:
            oval_file_content = request.FILES['file'].read()
            oval_file = save_file(constants.OVAL_TEMP, oval_file_content)
            generate_oval_report.delay(oval_file.name, sender_ip)
            return HttpResponse()


class ScanningReportReceiver(PostReceiver):
    """
    Receives scanning report,
    generates readable report
    """

    def post(self, request, *args, **kwargs):  # Receives xml, generates scanning reports
        sender_ip = get_ip_address(request)
        if 'file' in request.FILES:
            scanning_results = request.FILES['file'].read()
            scanning_file = save_file(constants.RESULTS_TEMP, scanning_results)
            generate_scanning_report.delay(scanning_file.name, sender_ip)
            return HttpResponse()


class UpgradeReportReceiver(PostReceiver):
    """
    Receives scanning report and installed packages with available updates on virtual machines,
    generates readable report with available updates for affected packages
    """

    def post(self, request, *args, **kwargs):
        sender_ip = get_ip_address(request)
        if 'file1' in request.FILES and 'file2' in request.FILES:
            scanning_results = request.FILES['file1'].read()
            available_updates = request.FILES['file2'].read()
            scanning_file = save_file(constants.RESULTS_TEMP, scanning_results)

dashboard/dashboard/templates/dashboard/reports/extended_scan_report.html
{% load report_tags %}
<div class="row">
    <div class="padding col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Threat</th>
                    <th>Severity</th>
                    <th>Impact</th>
                </tr>
            </thead>
            <tbody>
                {% for j in extended_scan_rows %}
                    <tr>
                        {% with i=forloop.counter0|stringformat:"s" %}
                            {% with name="name_"|add:i threat="threat_"|add:i severity="severity_"|add:i nvt="nvt_"|add:i %}
                                <th>{{ extended_scan_report.data|keyvalue:name }}</th>
                                <th>{{ extended_scan_report.data|keyvalue:threat }}</th>
                                <th>{{ extended_scan_report.data|keyvalue:severity }}</th>
                                <th>{{ extended_scan_report.data|keyvalue:nvt|keyvalue:"impact" }}</th>
                            {% endwith %}
                        {% endwith %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

dashboard/dashboard/templates/dashboard/reports/report.html
{% extends "dashboard/base.html" %}
{% load staticfiles i18n pipeline report_tags sekizai_tags %}

{% block less-inject %}

{% stylesheet 'report' %}

{% endblock %}

{% block content %}
    {% if error %}
        <p>{{ error }}</p>
    {% else %}
        <div class="container-fluid">
            <div class="info">
                <p>Virtual machine: {{ ip|default:"NA" }}</p>
                <div class="row frequencies">
                    {# Display frequencies #}
                    <div class="col-md-4">
                        List update frequency: {{ list_update_frequency|format_value_with_default:"NA" }}
                    </div>
                    <div class="col-md-4">
                        Basic scan frequency: {{ basic_scan_frequency|format_value_with_default:"NA" }}
                    </div>
                    <div class="col-md-4">
                        Upgrade report frequency: {{ upgrade_report_frequency|format_value_with_default:"NA" }}
                    </div>
                </div>
                <div class="row age-reports">
                    {# Display age of files and actual file #}
                    {% with title="Download file" %}
                        <div class="col-md-4">
                            Vulnerability list age: {{ oval_age|file_age:"NA" }}
                            <a class="no-color" data-toggle="tooltip" title="{{ title }}" href="{% url 'file' virtual_machine_number 'oval' %}"><i class="fa fa-file-text-o"></i></a>
                        </div>
                        <div class="col-md-4">
                            Scanning report age: {{ scanning_report_age|file_age:"NA" }}
                            <a class="no-color" data-toggle="tooltip" title="{{ title }}" href="{% url 'file' virtual_machine_number 'scanning_report' %}"><i class="fa fa-file-text-o"></i></a>
                        </div>
                        <div class="col-md-4">
                            Upgrade report age: {{ upgrade_report_age|file_age:"NA" }}
                            <a class="no-color" data-toggle="tooltip" title="{{ title }}" href="{% url 'file' virtual_machine_number 'upgrade_report' %}"><i class="fa fa-file-text-o"></i></a>
                        </div>
                    {% endwith %}
                </div>
            </div>

            <ul class="nav nav-tabs reports">
                <li class="active"><a data-toggle="tab" href="#scanning">Scanning Report</a></li>
                <li><a data-toggle="tab" href="#upgrade">Upgrade Report</a></li>
                <li><a data-toggle="tab" href="#extended-scan">Extended Scan Report</a></li>
            </ul>

            <div class="tab-content">
                <div id="scanning" class="tab-pane fade in active">
                    {% include 'dashboard/reports/scanning_report.html' %}
                </div>
                <div id="upgrade" class="tab-pane fade">
                    {% include 'dashboard/reports/upgrade_report.html' %}
                </div>
                <div id="extended-scan" class="tab-pane fade">
                    {% include 'dashboard/reports/extended_scan_report.html' %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

dashboard/dashboard/templates/dashboard/reports/scanning_report.html
<div class="row">
    <div class="padding col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>CVE</th>
                    <th>CVSS</th>
                    <th>Vulnerability result</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for definition in scanning_report %}
                    <tr data-toggle="collapse" data-target="#{{ forloop.counter0 }}"  class="accordion-toggle {% if definition.vulnerability_result %} danger {% else %} success {% endif %}">
                        <th class="no-wrap">{{ definition.cve.cve }}</th>
                        <th>{% if definition.cve.cvss == -1 or not definition.cve.cvss %}
                                N/A
                            {% else %}
                                {{ definition.cve.cvss }}
                            {% endif %}
                        </th>
                        <th>{{ definition.vulnerability_result }}</th>
                        <th>{{ definition.description }}</th>
                    </tr>
                    {% if definition.package_set.all %}
                        <tr>
                            <td colspan="5" class="hidden-row">
                                <div class="accordion-body collapse" id="{{ forloop.counter0 }}">
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Version</th>
                                                <th>Available version</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for package in definition.package_set.all %}
                                                <tr>
                                                    <th>{{ package.name }}</th>
                                                    <th>{{ package.version }}</th>
                                                    <th>{{ package.available_version }}&nbsp;<i class="fa fa-arrow-up blue"></i></th>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

dashboard/dashboard/templates/dashboard/reports/upgrade_report.html
<div class="row">
    <div class="padding col-md-12">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Package</th>
                    <th>Version</th>
                    <th>Available upgrade</th>
                </tr>
            </thead>
            <tbody>
                {% for package in upgrade_report %}
                    <tr>
                        <th>{{ package.name }}</th>
                        <th>{{ package.current_version }}</th>
                        <th>{{ package.available_version }}&nbsp;<i class="fa fa-arrow-up blue"></i></th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>